from langchain.llms import OpenAI
from langchain.chat_models import ChatOpenAI
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain
import tiktoken
from dotenv import load_dotenv
import os

load_dotenv()
openai_api_key = os.getenv('OPENAI_API_KEY')

with open("contentCreation/AINewsLetter/prepromptMail.txt", "r") as file:
    preprompt = file.read()
# print(preprompt)

template = (
    """
Max: {content}
AI :"""
)

prompt = PromptTemplate(input_variables=["content"], template=template)

llm = OpenAI(openai_api_key=openai_api_key)

llm_chain = LLMChain(
    llm=llm,
    prompt=prompt,
    verbose=True,
)


def getNbTokens(content):
    enc = tiktoken.get_encoding("cl100k_base")
    assert enc.decode(enc.encode("hello world")) == "hello world"

    # To get the tokeniser corresponding to a specific model in the OpenAI API:
    enc = tiktoken.encoding_for_model("gpt-3.5-turbo")
    res = enc.encode(content)
    print(len(res))
    return len(res)


def ask(content):
    while getNbTokens(content) > 3500:
        content = content[50:-50]
    res = llm_chain.predict(content=content).strip()
    if res[0] == '"':
        print("Removing the first and last char")
        res = res[1:-1]
    print(res)
    return res




if __name__ == "__main__":
    post = """Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec urna quis tortor venenatis cursus. Vestibulum pulvinar, lacus quis viverra ultrices, elit quam ultricies sem, vitae viverra eros augue nec turpis. Aenean tincidunt egestas orci. Suspendisse pretium ultricies mattis. Aenean et risus neque. Sed laoreet lacinia enim. Nullam bibendum lorem neque, eu vulputate arcu dictum ac. Quisque interdum feugiat metus id condimentum. Sed eget maximus enim, ac placerat ante. Aliquam ex arcu, auctor id odio eget, eleifend dignissim dui. Duis tincidunt elit velit. Ut mattis justo sem, eu malesuada purus viverra nec. Pellentesque consequat accumsan elementum. Cras sed egestas nibh, eu sagittis leo. Nunc ultricies posuere iaculis. Integer erat quam, interdum in nisi sit amet, sollicitudin tempor est.

Vivamus fringilla maximus augue, sit amet fermentum massa faucibus et. Aliquam erat volutpat. Nullam et arcu in tortor porttitor molestie. Proin nec magna dictum, sollicitudin dui in, porta nunc. Nunc a lacus blandit, vestibulum lorem efficitur, fermentum justo. Aliquam lobortis elit a risus tincidunt varius. Proin ullamcorper orci urna, eu pharetra nunc dignissim eget. Proin et justo dolor. Vivamus tortor dolor, feugiat ac sapien ac, scelerisque interdum ex. Vivamus viverra molestie est, et viverra risus. Duis ultricies justo eget interdum varius. Etiam vitae odio tellus. In hac habitasse platea dictumst. Aenean interdum ligula id placerat vehicula.

Donec semper arcu ac leo convallis, at gravida tortor vehicula. Phasellus hendrerit ullamcorper arcu, non luctus est porttitor eu. Suspendisse maximus cursus sapien sit amet elementum. Curabitur interdum justo mi, vitae aliquam neque viverra et. Proin eget erat elementum, rhoncus purus scelerisque, semper ligula. Aliquam in auctor orci, sit amet semper dui. Vestibulum ligula nunc, convallis vulputate pretium non, consequat et est. Sed porttitor pretium velit, sed ultricies turpis faucibus non. Ut a dui elementum, tempor turpis et, dictum magna. Nulla convallis lacus vitae sapien mattis vulputate. Nullam in urna lacus. Ut mattis cursus congue.

Duis id lorem sit amet enim rutrum dapibus. Sed ornare molestie purus, volutpat sollicitudin est congue sed. Ut nec elementum ipsum, quis tempus justo. Aenean molestie eros pellentesque tempus elementum. Duis aliquet id nulla quis dictum. Nulla vitae tincidunt neque, at blandit leo. Suspendisse id rutrum lacus. Nulla pharetra consectetur dui. Donec tempor augue eu mauris mattis suscipit ut sit amet urna. Aenean eu elit ut eros lacinia dignissim vel nec ligula. Nulla pellentesque sem sit amet eros dictum, vel volutpat elit viverra. Donec tempus orci viverra velit bibendum, nec venenatis diam egestas. Suspendisse euismod massa a ex dapibus, ut molestie lacus hendrerit. Etiam lacinia fringilla facilisis. Nullam porta, ipsum vel iaculis pulvinar, mi dui pharetra enim, vel convallis turpis mauris eu ex. Morbi euismod, ex ac laoreet interdum, velit est ullamcorper nulla, id ultrices ante augue ac libero.

Praesent rutrum, magna vel iaculis auctor, metus mauris blandit mi, sit amet luctus sapien nulla non sem. Ut aliquet arcu eget ex tristique auctor. Proin dapibus sit amet arcu eu luctus. Ut volutpat urna id augue pulvinar, viverra imperdiet enim pretium. Cras nec euismod sem. Fusce imperdiet hendrerit arcu eu eleifend. Vestibulum ac eros vitae eros tincidunt imperdiet. Fusce mauris sem, hendrerit a odio eget, maximus semper est. Aliquam at leo vel mauris posuere pellentesque ut vitae nunc. Mauris eget purus a orci efficitur elementum. Curabitur et ante et purus accumsan congue sit amet nec odio. Integer nec fermentum augue.

Sed est nibh, porta at imperdiet id, vulputate ut sapien. Nunc nec vestibulum dui. Aenean ac pellentesque odio. Maecenas interdum porttitor elit at porta. Proin vestibulum hendrerit est vel rutrum. Sed id erat ut metus cursus auctor. Praesent id ante non nunc ornare tempus at at nisl. Pellentesque id libero scelerisque nibh cursus iaculis sodales vel nunc. Phasellus iaculis nunc a lectus feugiat, ut laoreet libero porta. Nam vitae bibendum enim. Sed sodales metus at enim luctus scelerisque.

In imperdiet viverra elementum. Aenean pharetra augue eu arcu consequat, id imperdiet ligula feugiat. Pellentesque malesuada tempus efficitur. Aenean at enim suscipit, rutrum nisi non, interdum lacus. Duis eleifend quam vel sodales sollicitudin. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed pretium ex et ipsum finibus, nec rhoncus massa condimentum. Quisque commodo non urna quis venenatis. Fusce dapibus est tempor imperdiet auctor. Ut a tincidunt orci, vitae efficitur lacus. Aliquam finibus tincidunt maximus.

Etiam eu tellus mollis felis vestibulum aliquam non vel lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla ac molestie quam. Nullam sit amet dui eget diam sagittis congue. Vestibulum malesuada sem risus, mattis tempor lectus placerat vel. Vestibulum vestibulum est et orci mattis, ac mollis diam vestibulum. Integer condimentum, augue non varius congue, ipsum mauris posuere sapien, sed sollicitudin ligula massa consectetur nisi. Donec luctus eros sit amet luctus cursus. Nullam volutpat felis ornare, gravida lorem in, lacinia urna.

Morbi id vulputate tellus, id vulputate lorem. Fusce condimentum convallis enim ac dignissim. Aliquam erat volutpat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aenean at rhoncus ante. Cras eleifend lorem et vulputate suscipit. Duis et dolor ut velit sagittis vestibulum. Sed diam dui, accumsan vel risus sed, consequat bibendum risus. Donec pellentesque nisl ex, id euismod tellus faucibus id. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent tempus ultrices gravida. Nam commodo felis eu felis hendrerit, pulvinar auctor nunc interdum. Mauris iaculis condimentum eros, lobortis viverra magna aliquam porttitor. Curabitur commodo arcu ut congue vehicula. Vivamus nec lectus nec elit ultricies pharetra non eget erat.

Mauris molestie congue dui, et rutrum felis congue sed. Vestibulum posuere lacinia tortor vestibulum suscipit. Maecenas fringilla sem ac massa blandit, id sollicitudin turpis sagittis. Aliquam non eleifend libero. Pellentesque volutpat, odio ut facilisis viverra, risus nibh lobortis tortor, sit amet gravida ipsum sem nec neque. Sed auctor, urna id feugiat varius, purus velit molestie neque, id egestas massa magna eu neque. Aliquam erat volutpat. Suspendisse at rhoncus ipsum. Sed efficitur dui ac justo ullamcorper, ut bibendum lorem aliquet. Aliquam imperdiet imperdiet rhoncus.

Quisque commodo enim elit, non rutrum nisl euismod sit amet. Aenean nec eros eget orci molestie maximus. Maecenas sodales sit amet orci vitae congue. Curabitur tristique lacus ac arcu rutrum finibus. Aliquam nec porttitor nulla. Curabitur finibus efficitur congue. Sed ultrices, erat vel blandit gravida, nisl risus scelerisque nisl, quis porttitor est elit in magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. In non luctus nulla. Ut convallis iaculis lacus consequat facilisis.

Nulla sit amet tempus urna. Aenean lorem nulla, accumsan eu lacus eu, suscipit ullamcorper tellus. Aliquam erat volutpat. Vestibulum hendrerit sollicitudin velit vel volutpat. Nam a pulvinar arcu, non lacinia quam. Mauris lacinia lorem ultrices nibh aliquam, at fermentum lectus hendrerit. Vestibulum felis leo, convallis eu iaculis a, venenatis quis dui. Cras eget ipsum quam. Fusce vestibulum maximus auctor. Sed erat lectus, consequat eget orci a, condimentum ullamcorper tellus. Morbi a magna at risus vehicula facilisis. Curabitur at purus consequat, dictum nibh id, vehicula sem.

Suspendisse eu aliquam lacus. Nulla viverra viverra egestas. Fusce tempus facilisis ex eu cursus. Sed sit amet pretium lectus. Integer odio quam, rutrum at nisl quis, egestas bibendum nisl. Quisque tincidunt nulla hendrerit diam sodales, id fringilla purus aliquet. Etiam euismod ut libero id fringilla. In posuere sapien velit, ut ultrices dui laoreet mattis. Integer congue eget leo ut commodo. Maecenas bibendum, ipsum ut faucibus accumsan, tortor orci eleifend orci, ac venenatis ante tellus et urna. Vestibulum imperdiet, ante at mollis luctus, justo neque aliquam tortor, eu rhoncus velit orci a dui. Vivamus quis sem finibus, suscipit sem non, sodales sapien. Praesent sed pellentesque tellus. Nunc tincidunt dolor quis odio tempor, vitae varius tortor auctor.

Aenean ut felis sed augue faucibus rutrum a ac dui. Praesent at nulla aliquam, auctor dui at, lacinia libero. Ut a pulvinar mauris, in imperdiet lacus. Aliquam eleifend arcu in pretium imperdiet. Vestibulum finibus erat nec aliquet sodales. Sed rhoncus rhoncus est, at finibus ex sollicitudin non. Aliquam id bibendum ex. Nam mattis, mi vitae vulputate vulputate, ante elit porttitor ex, at aliquet ex ex ac lectus. Sed ullamcorper, risus et gravida sollicitudin, enim metus tincidunt tortor, eget tincidunt ligula orci ut libero. Donec a pretium mauris. Proin id elit id urna suscipit posuere ut quis dolor. Etiam sit amet urna eu lorem egestas bibendum. Nulla facilisi.

Maecenas euismod lorem ac posuere tincidunt. Donec sed porttitor tortor, ac lacinia ligula. Proin sit amet augue et elit iaculis malesuada. Nam lobortis porttitor elit, vestibulum convallis nibh ultricies in. Nulla volutpat imperdiet nisi, eget dapibus nisl ullamcorper vel. Praesent id ante justo. Suspendisse gravida mattis dui ut malesuada. Duis ac finibus orci, in dapibus felis. Donec pharetra arcu erat, a porttitor nunc iaculis eget. Nunc pretium, ex euismod sodales egestas, dui tortor faucibus est, id pulvinar nulla eros nec justo. Pellentesque enim justo, vestibulum at ipsum nec, aliquet tempor ante. Nam consequat, tellus hendrerit elementum lacinia, ligula felis tempus ante, at porttitor massa leo at risus. Nam interdum, turpis at aliquet rhoncus, sem sem facilisis leo, et euismod orci ipsum sed elit. Aenean varius ante gravida, laoreet velit in, lacinia elit.

Maecenas feugiat, justo ut pretium pretium, tellus elit molestie dui, vel elementum tellus arcu cursus nisl. Mauris felis neque, venenatis et pulvinar a, malesuada et metus. Proin tincidunt, felis at semper sodales, orci elit rutrum libero, eu tempor sem orci pharetra odio. Proin suscipit, erat sit amet ultricies commodo, nulla leo condimentum nibh, eget suscipit dolor sem ultrices urna. Donec ac mollis erat, ac aliquam risus. In imperdiet est ut nunc auctor, a pellentesque mi sollicitudin. Phasellus imperdiet pulvinar metus non lacinia. Phasellus vestibulum dignissim nulla ut posuere. Nunc in ex non quam volutpat ornare eget a diam. Integer et justo vitae lorem vestibulum sodales. Proin et nunc a urna mollis tincidunt id sit amet dolor. Nullam pulvinar magna sed nunc ultrices, sit amet pretium ante placerat. Cras eu luctus ante. Donec non nisi ut justo efficitur interdum.

Cras lacinia eu ex ac ornare. Pellentesque gravida dignissim lorem ac maximus. Etiam lacinia nibh sed nisl pulvinar porttitor. Sed sit amet vestibulum urna. Aliquam erat volutpat. Integer dapibus vel nibh at dignissim. Proin commodo eget velit consequat fermentum. In hac habitasse platea dictumst. Morbi massa erat, rhoncus vel malesuada a, commodo in ante. Etiam eu scelerisque risus, imperdiet vehicula nulla. Donec vulputate consequat sapien et blandit. Sed sit amet risus eget magna ultrices maximus accumsan vel metus. Aliquam et purus id tellus egestas hendrerit sed eget nisi. Phasellus ut nulla at velit convallis imperdiet.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Maecenas molestie ligula fermentum purus ultricies fermentum nec venenatis ante. Maecenas eleifend quam augue, vel bibendum eros rhoncus nec. Fusce pulvinar, massa ut vestibulum tempor, orci massa eleifend turpis, vitae varius nulla dui faucibus enim. Donec id elit pharetra, commodo sapien eu, varius quam. Curabitur consequat, nulla finibus placerat egestas, elit enim tincidunt justo, id mollis tortor felis vel nisl. Nullam pulvinar molestie lacus vitae lacinia. Praesent porta nulla consequat neque vehicula finibus. Integer lobortis turpis augue, a consectetur nulla condimentum nec. Integer blandit fermentum ipsum, interdum accumsan nisi. Maecenas at orci vel urna pulvinar posuere. Nunc viverra est ac massa porttitor, sed rutrum nisi imperdiet.

Pellentesque ultrices lectus nunc, vitae malesuada tellus convallis sit amet. Aliquam rutrum leo et convallis egestas. In laoreet leo non metus ultricies pharetra. Nullam sollicitudin metus at fringilla rhoncus. Cras risus tellus, ultricies facilisis eros vel, maximus lacinia velit. Duis blandit sapien sodales odio aliquet imperdiet. Integer euismod consequat justo nec placerat.

Vivamus tincidunt faucibus lectus quis interdum. Sed enim ligula, semper sit amet aliquam non, suscipit quis nisl. Suspendisse ut fringilla urna. Pellentesque vitae rhoncus purus. Integer imperdiet magna est, vitae mattis sem feugiat euismod. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent dignissim lorem ut nibh placerat mollis. Ut ornare dignissim ullamcorper. Vestibulum ut mauris sed erat finibus mollis. Proin vestibulum dictum ligula sit amet dapibus. Sed facilisis suscipit tempor. Aliquam vel nisl quis massa laoreet volutpat. Maecenas et urna quis diam lacinia aliquam. Proin varius ultrices pellentesque.

Nam ut mi elit. Nam turpis ligula, volutpat non nulla sed, bibendum vulputate urna. Integer eu nunc est. Vestibulum eu elementum turpis. Praesent non bibendum nulla. Suspendisse in urna commodo, tincidunt dolor pharetra, accumsan tortor. Mauris mollis diam lacus, quis euismod nibh malesuada at. Nam dolor arcu, fringilla aliquet pellentesque ut, dignissim at sapien. Cras a erat tempus, accumsan nisi sed, consequat quam. Donec fermentum imperdiet sem a rhoncus. Suspendisse vitae sagittis enim. Integer auctor, est nec facilisis venenatis, dolor eros pretium leo, ac interdum mi enim quis purus. Nulla urna tellus, pretium at nisi eget, convallis luctus magna. Proin sit amet molestie diam. Nam fringilla leo ut justo venenatis, eu vulputate sapien venenatis. Sed non tincidunt mauris.

Pellentesque eget metus mauris. Curabitur et egestas nibh. Vestibulum facilisis diam id orci auctor bibendum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras venenatis lacus eget euismod lobortis. Sed sollicitudin ipsum non purus convallis, nec cursus elit finibus. Praesent sodales enim feugiat, mollis lacus ac, facilisis nibh. Etiam sit amet est ac neque dictum euismod eget porta enim. Curabitur porta nisi feugiat, convallis lorem et, interdum erat. Morbi accumsan et magna ac aliquet. Proin sit amet nunc posuere, vehicula justo eu, condimentum odio. Nam in leo luctus, vestibulum ex vehicula, feugiat ex. Nulla lorem eros, suscipit blandit enim vitae, mollis interdum metus. Fusce ut augue ut purus posuere condimentum. Donec tristique mattis imperdiet.

Morbi at blandit elit. Nam nec auctor risus, id semper lorem. Cras in felis mauris. Vivamus sed massa viverra, hendrerit turpis ut, maximus mi. Morbi et tortor sollicitudin lacus finibus iaculis ac ut nulla. Etiam varius nec sapien non pulvinar. Nam et tristique est. In hac habitasse platea dictumst. Ut nisi tortor, bibendum id turpis ac, tincidunt auctor dui. Etiam eget odio sed arcu rutrum placerat non eget ante. Sed pulvinar lobortis mi vitae feugiat. Pellentesque in est non urna ultrices egestas. Integer justo odio, elementum a laoreet sit amet, dignissim ut enim.

Duis congue ligula nisl, vitae viverra enim iaculis in. Praesent accumsan neque varius massa dignissim molestie. Phasellus ante risus, luctus vel bibendum ut, consectetur nec odio. Quisque eget nisl nec felis interdum suscipit ut in lorem. Quisque quis malesuada justo. Maecenas congue ante magna, sed rutrum purus porta non. Nam eu nunc a eros euismod finibus. Vivamus ac fringilla ipsum, nec sollicitudin mauris. Donec augue arcu, cursus vel molestie ut, placerat quis nisl. Vivamus nulla ligula, consectetur sed tempor non, congue non dolor. Etiam malesuada, felis sit amet hendrerit semper, eros ante sollicitudin tortor, id facilisis neque ante non sapien. Ut pellentesque quis ante nec blandit. Suspendisse nec est sit amet turpis blandit consequat eget ac elit. Aliquam ornare tellus nec ipsum mollis, congue egestas tortor auctor.

Aliquam accumsan eget eros a placerat. Cras iaculis libero in risus mattis pulvinar. Nulla lorem nibh, ultrices in vulputate ut, condimentum non nibh. Donec ultrices sapien eget pellentesque finibus. Nunc nec euismod quam. Morbi a turpis eu sem porttitor facilisis. Etiam ornare, mi quis euismod varius, sapien nibh gravida magna, sed consequat eros purus vel eros. Ut id libero ex. Morbi varius nibh sed quam laoreet molestie. Nunc erat odio, facilisis nec enim vitae, tempor convallis tellus. Mauris nec metus a orci auctor bibendum.

Donec tempus facilisis mauris, a fringilla est viverra non. Ut vulputate ultrices tincidunt. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Fusce vel metus sit amet nulla semper venenatis in a velit. Vivamus eget venenatis est. Pellentesque scelerisque pulvinar dolor sit amet pulvinar. Curabitur et ex sed libero finibus ullamcorper quis id odio. Nulla tempor ex metus, a convallis massa tincidunt non.

Maecenas dignissim ornare ullamcorper. Suspendisse rutrum ac purus quis pretium. Morbi id iaculis purus, vitae porttitor elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc molestie libero ut lorem rhoncus blandit. Donec ut mattis odio. Nunc ullamcorper convallis pretium. Nunc ornare molestie bibendum.

In quis nulla sit amet elit tempor aliquet. Suspendisse feugiat erat nisl, non ornare ante mattis ut. Sed convallis turpis ultrices volutpat dapibus. Nam fringilla mauris nulla, sed tincidunt nulla bibendum eu. Donec bibendum, tellus a condimentum laoreet, lacus turpis imperdiet metus, quis cursus est magna vehicula nibh. Ut blandit justo eu consectetur semper. Pellentesque vitae leo vitae mi rutrum aliquam nec ac turpis. Quisque faucibus porttitor commodo. Vestibulum malesuada facilisis purus convallis venenatis. Fusce ut risus id justo gravida sodales eget cursus justo. Fusce varius lorem tellus, vitae auctor massa venenatis pulvinar. Suspendisse euismod faucibus arcu et pretium. Vivamus commodo, nisl nec vulputate rutrum, odio orci hendrerit metus, vel egestas lectus magna eu felis. Quisque in felis euismod, tempus tellus eu, elementum nunc.

Donec sapien sem, feugiat ac leo quis, scelerisque aliquet mauris. Aenean efficitur justo sit amet consequat vulputate. Pellentesque et ultrices purus, vel vestibulum arcu. Integer mattis mauris magna, ut lacinia purus euismod vitae. Sed ac mi rhoncus arcu rhoncus fermentum id ac libero. Quisque sit amet pretium arcu. Nulla porttitor rhoncus leo, nec elementum eros maximus a. Nam congue gravida metus vitae hendrerit. Morbi tempus nec metus id iaculis. Aenean a enim arcu. In accumsan posuere mi et suscipit. Pellentesque sed mi quis massa laoreet fermentum.

Aliquam a risus ut augue tristique mattis. Praesent id mi est. Suspendisse interdum vitae metus id condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent lobortis imperdiet velit vel sagittis. Cras ut sollicitudin libero, at blandit neque. Maecenas dapibus massa accumsan convallis maximus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc eleifend in augue vel rhoncus.

Praesent tincidunt lorem et ipsum elementum, egestas efficitur nibh iaculis. Sed congue ac nisl id molestie. Sed et sapien eget dui maximus dapibus eu quis nibh. Sed ultricies iaculis elit. Fusce id leo sit amet sapien iaculis dictum sit amet sit amet augue. Phasellus nec mattis urna. Vestibulum mattis tortor at massa finibus feugiat. Praesent eu vestibulum odio, nec lacinia velit. Aliquam ut magna convallis, imperdiet justo non, accumsan nisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed aliquet risus ante. Proin ac mauris ut ipsum sollicitudin tincidunt sed ut ex. In semper erat id erat molestie, blandit rhoncus augue tempus. Integer tortor orci, mattis eu dui mollis, aliquet vehicula massa.

In gravida a arcu nec vehicula. Aenean porttitor turpis eu nisi suscipit consectetur. Integer nec molestie purus. Nullam quis finibus enim. Donec pulvinar faucibus luctus. Quisque vitae ante sit amet sapien pretium laoreet. Curabitur dolor elit, elementum eu enim et, ullamcorper porttitor lacus. Aliquam erat volutpat. Cras elementum risus at urna mollis pharetra.

Proin laoreet auctor magna, eu tincidunt sem. Pellentesque eget velit sapien. Aenean at ante sodales, accumsan ex vitae, tempus ligula. Etiam tellus metus, auctor sit amet arcu sit amet, tempus rutrum mi. Integer cursus, enim in congue suscipit, elit lectus porta risus, eu tempus nunc diam non augue. Vestibulum arcu mi, euismod a purus ut, blandit viverra nisl. Donec scelerisque, libero vel dapibus ornare, arcu libero bibendum lorem, nec maximus nisi sapien eget justo. Curabitur imperdiet metus enim, id semper magna egestas tincidunt. Etiam malesuada magna eu vehicula semper.

Etiam condimentum auctor libero ac varius. Proin sem est, lobortis in risus vel, scelerisque viverra mi. Pellentesque sagittis dui eu purus mattis scelerisque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ipsum lacus, tincidunt vel eros eleifend, rutrum ultrices nulla. Quisque interdum turpis quis erat lobortis elementum. Aenean ut odio nec eros iaculis lobortis. Donec lacinia id purus et porta. Nullam ornare tristique rhoncus. Nulla a erat laoreet, convallis ligula a, tincidunt risus. Integer ut massa velit. Nulla risus metus, tempor a risus at, porta maximus est. Pellentesque sagittis eu lorem sit amet luctus. In faucibus euismod sagittis. Etiam a rhoncus tortor.

Sed non quam sit amet leo tempus venenatis sed ac erat. Cras ligula urna, accumsan nec ante ac, congue scelerisque lorem. Sed mattis sem vel commodo luctus. Nulla aliquet pretium sem quis blandit. Mauris semper, lorem vel vulputate ornare, erat mi aliquam lacus, vel aliquet enim sem sed est. Integer elementum lacinia tempus. Vivamus in vestibulum metus. Praesent varius mauris eget eros condimentum, et convallis nulla sagittis. Vestibulum a diam id mauris euismod mattis ut ut nunc. Vivamus egestas odio in luctus egestas. Cras fermentum eu nisi non consequat. Donec lobortis dapibus facilisis.

Sed vitae vulputate eros. Nullam pellentesque eu felis congue posuere. Donec luctus congue libero, sit amet efficitur ante pulvinar eu. Cras ut magna quis eros sollicitudin venenatis. Maecenas ut ante in ligula tristique tincidunt. Sed eu ornare mauris. Praesent lacinia enim dolor, id consequat dui facilisis nec. Nunc suscipit magna eget pretium convallis. Maecenas placerat tellus at arcu bibendum interdum. Donec eleifend molestie felis id bibendum. In vestibulum, libero a scelerisque dictum, diam nisl aliquam turpis, ac semper ligula enim eget diam.

Aenean maximus velit id lacus ultricies tincidunt. Vivamus interdum orci nec quam maximus vulputate sed sed lectus. Cras eu rhoncus nulla. Sed porttitor bibendum tincidunt. Curabitur sed consectetur metus. Pellentesque felis tellus, condimentum et lectus quis, feugiat posuere tortor. Aenean nibh elit, interdum vel ultrices a, feugiat ut mauris. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc mattis convallis purus at fermentum. Sed at mattis mi. Praesent quis efficitur nunc, feugiat egestas augue. Nunc bibendum dui quis ex tempor varius. Integer justo massa, consectetur quis diam sed, cursus interdum ligula."""
    ask(post)
    post = """Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec urna quis tortor venenatis cursus. Vestibulum pulvinar, lacus quis viverra ultrices, elit quam ultricies sem, vitae viverra eros augue nec turpis. Aenean tincidunt egestas orci. Suspendisse pretium ultricies mattis. Aenean et risus neque. Sed laoreet lacinia enim. Nullam bibendum lorem neque, eu vulputate arcu dictum ac. Quisque interdum feugiat metus id condimentum. Sed eget maximus enim, ac placerat ante. Aliquam ex arcu, auctor id odio eget, eleifend dignissim dui. Duis tincidunt elit velit. Ut mattis justo sem, eu malesuada purus viverra nec. Pellentesque consequat accumsan elementum. Cras sed egestas nibh, eu sagittis leo. Nunc ultricies posuere iaculis. Integer erat quam, interdum in nisi sit amet, sollicitudin tempor est.

Vivamus fringilla maximus augue, sit amet fermentum massa faucibus et. Aliquam erat volutpat. Nullam et arcu in tortor porttitor molestie. Proin nec magna dictum, sollicitudin dui in, porta nunc. Nunc a lacus blandit, vestibulum lorem efficitur, fermentum justo. Aliquam lobortis elit a risus tincidunt varius. Proin ullamcorper orci urna, eu pharetra nunc dignissim eget. Proin et justo dolor. Vivamus tortor dolor, feugiat ac sapien ac, scelerisque interdum ex. Vivamus viverra molestie est, et viverra risus. Duis ultricies justo eget interdum varius. Etiam vitae odio tellus. In hac habitasse platea dictumst. Aenean interdum ligula id placerat vehicula.

Donec semper arcu ac leo convallis, at gravida tortor vehicula. Phasellus hendrerit ullamcorper arcu, non luctus est porttitor eu. Suspendisse maximus cursus sapien sit amet elementum. Curabitur interdum justo mi, vitae aliquam neque viverra et. Proin eget erat elementum, rhoncus purus scelerisque, semper ligula. Aliquam in auctor orci, sit amet semper dui. Vestibulum ligula nunc, convallis vulputate pretium non, consequat et est. Sed porttitor pretium velit, sed ultricies turpis faucibus non. Ut a dui elementum, tempor turpis et, dictum magna. Nulla convallis lacus vitae sapien mattis vulputate. Nullam in urna lacus. Ut mattis cursus congue.

Duis id lorem sit amet enim rutrum dapibus. Sed ornare molestie purus, volutpat sollicitudin est congue sed. Ut nec elementum ipsum, quis tempus justo. Aenean molestie eros pellentesque tempus elementum. Duis aliquet id nulla quis dictum. Nulla vitae tincidunt neque, at blandit leo. Suspendisse id rutrum lacus. Nulla pharetra consectetur dui. Donec tempor augue eu mauris mattis suscipit ut sit amet urna. Aenean eu elit ut eros lacinia dignissim vel nec ligula. Nulla pellentesque sem sit amet eros dictum, vel volutpat elit viverra. Donec tempus orci viverra velit bibendum, nec venenatis diam egestas. Suspendisse euismod massa a ex dapibus, ut molestie lacus hendrerit. Etiam lacinia fringilla facilisis. Nullam porta, ipsum vel iaculis pulvinar, mi dui pharetra enim, vel convallis turpis mauris eu ex. Morbi euismod, ex ac laoreet interdum, velit est ullamcorper nulla, id ultrices ante augue ac libero.

Praesent rutrum, magna vel iaculis auctor, metus mauris blandit mi, sit amet luctus sapien nulla non sem. Ut aliquet arcu eget ex tristique auctor. Proin dapibus sit amet arcu eu luctus. Ut volutpat urna id augue pulvinar, viverra imperdiet enim pretium. Cras nec euismod sem. Fusce imperdiet hendrerit arcu eu eleifend. Vestibulum ac eros vitae eros tincidunt imperdiet. Fusce mauris sem, hendrerit a odio eget, maximus semper est. Aliquam at leo vel mauris posuere pellentesque ut vitae nunc. Mauris eget purus a orci efficitur elementum. Curabitur et ante et purus accumsan congue sit amet nec odio. Integer nec fermentum augue.
"""
    ask(post)
